# Generated by Django 6.1.1 on 2026-09-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Department',
                'verbose_name_plural': 'Career Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Enter one responsibility per line.')),
                ('requirements', models.TextField(blank=True, help_text='Enter one requirement per line.')),
                ('preferred_qualifications', models.TextField(blank=True, help_text='Enter one preferred qualification per line.')),
                ('required_skills', models.TextField(blank=True, help_text='Enter skills separated by commas.')),
                ('benefits', models.TextField(blank=True, help_text='Enter one benefit per line.')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=20)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On-site')], default='REMOTE', max_length=20)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('JUNIOR', 'Junior'), ('MID', 'Mid Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('EXPERT', 'Expert')], default='ENTRY', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Example: Mumbai, India or Remote.', max_length=150)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('salary_period', models.CharField(default='year', help_text='Example: year, month, hour.', max_length=30)),
                ('application_url', models.URLField(blank=True)),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='careers.careerdepartment')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
