# Generated by Django 6.1.1 on 2026-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('WEB', 'Web Development'), ('MOBILE', 'Mobile Development'), ('AI', 'Artificial Intelligence'), ('SOFTWARE', 'Software Development'), ('ECOMMERCE', 'E-Commerce'), ('BUSINESS', 'Business Website'), ('API', 'API Development'), ('UI_UX', 'UI/UX Design'), ('AUTOMATION', 'Automation'), ('OTHER', 'Other')], default='WEB', max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_industry', models.CharField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('technologies', models.TextField(blank=True, help_text='Enter technology names separated by commas.')),
                ('features', models.TextField(blank=True, help_text='Enter one project feature per line.')),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('MAINTENANCE', 'Maintenance'), ('ARCHIVED', 'Archived')], default='COMPLETED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
