# Generated by Django 6.1.1 on 2026-09-05 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('project_type', models.CharField(choices=[('WEBSITE', 'Website'), ('WEB_APP', 'Web Application'), ('MOBILE_APP', 'Mobile Application'), ('ECOMMERCE', 'E-Commerce'), ('AI_ML', 'AI / Machine Learning'), ('SOFTWARE', 'Software Development'), ('API', 'API Development'), ('AUTOMATION', 'Business Automation'), ('UI_UX', 'UI/UX Design'), ('OTHER', 'Other')], default='WEBSITE', max_length=30)),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('project_description', models.TextField(help_text='Detailed description of the project.')),
                ('required_features', models.TextField(blank=True, help_text='Enter one required feature per line.')),
                ('existing_website', models.URLField(blank=True)),
                ('budget_range', models.CharField(choices=[('UNDER_25K', 'Under ₹25,000'), ('25K_50K', '₹25,000 - ₹50,000'), ('50K_1L', '₹50,000 - ₹1,00,000'), ('1L_3L', '₹1,00,000 - ₹3,00,000'), ('3L_5L', '₹3,00,000 - ₹5,00,000'), ('ABOVE_5L', 'Above ₹5,00,000'), ('CUSTOM', 'Custom Budget')], default='CUSTOM', max_length=20)),
                ('timeline', models.CharField(choices=[('ASAP', 'As Soon As Possible'), ('ONE_MONTH', 'Within 1 Month'), ('1_TO_3_MONTHS', '1-3 Months'), ('3_TO_6_MONTHS', '3-6 Months'), ('6_PLUS_MONTHS', '6+ Months'), ('FLEXIBLE', 'Flexible')], default='FLEXIBLE', max_length=30)),
                ('preferred_technologies', models.TextField(blank=True, help_text='Enter preferred technologies separated by commas.')),
                ('additional_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('CONTACTED', 'Client Contacted'), ('PROPOSAL_SENT', 'Proposal Sent'), ('NEGOTIATION', 'Negotiation'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes visible only to administrators.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('proposal_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('estimated_quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='quotes.quoterequest')),
            ],
        ),
    ]
